image: maven:3.6.3-jdk-11

# DinD service is required for Testcontainers
services:
  - docker:dind

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  # Instruct Testcontainers to use the daemon of DinD.
  DOCKER_HOST: "tcp://docker:2375"
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - release-start
  
cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - whoami
    - printenv    
    - mvn clean install -DskipTests=true
#  only:
#    - master

test:
  stage: test
  script:
    - mvn clean test
#  only:
#    - master

release-start:
  stage: release-start
  when: manual
  script:
    # we need to extract the ssh/git URL as the runner uses a tokenized URL
    - export CI_PUSH_REPO=`echo $CI_BUILD_REPO | perl -pe 's#.*@(.+?(\:\d+)?)/#git@\1:#'`
    - echo $CI_PUSH_REPO
    # runner runs on a detached HEAD, create a temporary local branch for editing
    - git config --global user.name "My Runner"
    - git config --global user.email "runner@gitlab.example.org"
    - git remote set-url --push origin "${CI_PUSH_REPO}"
    - git checkout develop
    - git checkout -b ci_processing
    # make your changes
    - touch test.txt
    # push changes
    # always return true so that the build does not fail if there are no changes
    - git commit -am "release-start"
    - git push --all
    

    
#deploy:
#  stage: deploy
#  script:
#    - mvn $MAVEN_CLI_OPTS deploy
#  only:
#    - master
