image: maven:3.6.3-jdk-11

# DinD service is required for Testcontainers
services:
  - docker:dind

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  # Instruct Testcontainers to use the daemon of DinD.
  DOCKER_HOST: "tcp://docker:2375"
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2
  
cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - whoami
    - printenv    
    - mvn clean install -DskipTests=true
#  only:
#    - master

test:
  stage: test
  script:
    - mvn clean test
#  only:
#    - master
    
#deploy:
#  stage: deploy
#  script:
#    - mvn $MAVEN_CLI_OPTS deploy
#  only:
#    - master
